### ISSUE TITLE
New release/tag

### ISSUE THREAD

**Issue by okdewit** [beyondcode/laravel-self-diagnosis#105]
Would it be possible to tag a new (major?) version, as php 8 is allowed in composer.json but only on the main branch?

**Comment by akalongman** [comment]
+1

**Comment by SeoFood** [comment]
yes pls tag the new version

**Comment by daanklijn** [comment]
I would like that as well!
@mpociot

**Comment by Jackpump** [comment]
I would like that change too.

**Comment by robertatcd** [comment]
+1, in my case it's the updated semver dependency in composer.json I need.

**Comment by HDVinnie** [comment]
@mpociot any update on this?
