### ISSUE TITLE
ComposerIsUpToDate fails on production

### ISSUE THREAD

**Issue by fitztrev** [beyondcode/laravel-self-diagnosis#13]
It looks like it fails because it can't find any of my `require-dev` packages. Could the check use `--no-dev` for production environments?

**Comment by mpociot** [comment]
I only perform a dry run of composer install. So everything that is in your lock file will be checked. Maybe you don’t have a lock file?

**Comment by fitztrev** [comment]
No, I do have a lock file.

`composer install --dry-run` will also include `require-dev` packages.

**Comment by mpociot** [comment]
Oh you’re  right. Then we should split it up in two separate checks and add them to the development and production keys.

**Comment by mpociot** [comment]
Fixed in https://github.com/beyondcode/laravel-self-diagnosis/commit/b21b10ec35c8ca0389d104a24470ed68666d7e73
