### ISSUE TITLE
 Class 'Memcached' not found

### ISSUE THREAD

**Issue by napestershine** [beyondcode/laravel-self-diagnosis#2]
I am trying to use in lumen. I am using Redis for caching. but it gives following error

` Class 'Memcached' not found`

`Thanks

**Comment by VictorAvelar** [comment]
I think you can publish the assets and just remove the check for Memcached, also you can use this as a base and create your own for Redis :smile: hope it helps.

**Comment by mpociot** [comment]
Hm, there is no test that actually performs something with Memcached.

**Comment by napestershine** [comment]
its working fine. Thanks
