### ISSUE TITLE
Make configuration more flexible

### ISSUE THREAD

**Issue by Namoshek** [beyondcode/laravel-self-diagnosis#25]
I think there would be major advantages if we adjusted the configuration to something like the following (please be aware that the check configs do not need to make any sense, it is only for illustration; also shortened the config a bit...):

```
return [

    /*
     * Common checks that will be performed on all environments.
     */
    'checks' => [
        \BeyondCode\SelfDiagnosis\Checks\AppKeyIsSet::class,
        \BeyondCode\SelfDiagnosis\Checks\CorrectPhpVersionIsInstalled::class,
        \BeyondCode\SelfDiagnosis\Checks\DatabaseCanBeAccessed::class => [
            'check_db_version' => true,
            'required_version' => '>= '14.7.3',
        ],
    ],

    /*
     * Environment specific checks.
     */
    'environment_checks' => [
        'production' => [
            \BeyondCode\SelfDiagnosis\Checks\Production\XDebugIsNotEnabled::class,
            \BeyondCode\SelfDiagnosis\Checks\Production\DebugModeIsNotEnabled::class,
            \BeyondCode\SelfDiagnosis\Checks\SupervisorJobRunning::class => [
                'runs_less_than' => 300, // seconds since last restart
            ],
        ],
        'development' => [
            \BeyondCode\SelfDiagnosis\Checks\Development\ConfigurationIsNotCached::class,
            \BeyondCode\SelfDiagnosis\Checks\Development\RoutesAreNotCached::class,
        ],
        'staging' => [
            \BeyondCode\SelfDiagnosis\Checks\Production\ExtensionsAreNotEnabled::class => [
                'extensions' => ['xdebug','zlib'],
            ],
            \BeyondCode\SelfDiagnosis\Checks\Development\RoutesAreNotCached::class,
        ],
    ],

];
```
(Please note that I added the not existing checks `SupervisorJobRunning` and `ExtensionsAreNotEnabled` in the example to illustrate nice use cases.)

Clearly, this would require us to change the existing `Check` interface slightly:

```
interface Check
{
    /**
     * Perform the actual verification of this check.
     *
     * @param array $config
     * @return bool
     */
    public function check(array $config) : bool;
}
```
(It is discussable if the `$config` should also be passed to the other functions, especially the `message()` function for error reporting. Or if it should simply be passed to the checks constructor (not enforceable via interface).)

If the currently existing part of the configuration where different aliases are mapped to the `production` environment is required, it can easily be added to the new configuration as simple mapping:

```
/*
 * A list of environment aliases mapped to the actual environment configuration.
 */
'environment_aliases' => [
    'prod' => 'production',
    'live' => 'production',
],
```

Please let me know what you think of this as it suggests no backwards-compatible change. Of course I would be willing to implement it if it is considered a good idea.

**Comment by mpociot** [comment]
I like this a lot. I thought about this when I saw PR #19 as I like the fact that the configuration actually belongs to the check that will be performed. 

And I don’t mind a breaking change, this is still a 0.x release and this will bring it close to 1.0 :)

**Comment by Namoshek** [comment]
Awesome! I'll try to put a PR together in the evening then. Should be straight forward to implement anyway.
