### ISSUE TITLE
Doesn't work with laravel 5.2

### ISSUE THREAD

**Issue by ZR87** [beyondcode/laravel-self-diagnosis#27]
laravel-self-diagnosis: **0.3.0**
laravel **5.2**
os: mac HighSierra
php: 7.1

Hello!
Installed without problem,  but seems it doesn't work together with laravel 5.2.
The `self-siagnose` artisan command doesn't  even appear in the list of the commands available.

**Comment by mpociot** [comment]
For Laravel 5.4 and below, you need to register the service provider in your config/app.php file. Did you register it?

**Comment by ZR87** [comment]
Woops! forgot it totally! Thank you @mpociot !
