### ISSUE TITLE
Is there a way to add  --ignore-platform-reqs to the automatic composer update call?

### ISSUE THREAD

**Issue by nat-mystudiosessions** [beyondcode/laravel-self-diagnosis#41]
Awesome job on self-diagnosis!

I'm running on Windows with Laravel Horizon. Horizon requires the ext-pcntl php extension which isn't available for Windows (sad for me). So, to get around it I run

```composer update --ignore-platform-reqs ext-pcntl```

This way I can still work with Horizon on my unix production server.
Is there a way to add the ```--ignore-platform-reqs flag``` to laravel-self-diagnosis? If not, then I get the output in the screenshot below.

Thanks!

![image](https://user-images.githubusercontent.com/21112371/42898997-bc2008f0-8a92-11e8-83ca-4953880c16e1.png)

**Comment by Namoshek** [comment]
Seems fairly straight forward to implement. But it should be made configurable. We could introduce a new `additional_options` configuration parameter for the composer checks for example.
