### ISSUE TITLE
Locale check failing

### ISSUE THREAD

**Issue by fitztrev** [beyondcode/laravel-self-diagnosis#48]
Result is: "The function "shell_exec" is not defined or disabled, so we cannot check the locales."

`shell_exec('locale -a')` works when running from `php artisan tinker`, but not from the Locale checker.

The `isFunctionAvailable()` method incorrectly returns false. I think it's because of this conditional:

```php
true === stripos(ini_get('disable_functions'), $function)
```

My `disable_functions` is empty in my php.ini.

**Comment by Namoshek** [comment]
A PR with a fix has already been merged, but no new version has been released yet. See #44.

**Comment by fitztrev** [comment]
@Namoshek  Thanks 👍
