### ISSUE TITLE
Support for lumen

### ISSUE THREAD

**Issue by napestershine** [beyondcode/laravel-self-diagnosis#5]
HI

I am doing API development in Lumen. Can you please add support for lumen?

Thanks

**Comment by cgoosey1** [comment]
Nice package, I was curious to test it with Lumen as well. You need to add 
```
 $app->register(\BeyondCode\SelfDiagnosis\SelfDiagnosisServiceProvider::class);
```
in bootstrap/app.php.

Then if you try and run it it will fail on config_path/public path not being defined.
Not sure if you really need public path for checks, my application worked ok by me adding this snippet in app.php:

```
function config_path($path = '')
{
    return app()->basePath() . '/config' . ($path ? '/' . $path : $path);
}
```

So I suppose for Lumin support an addition to the documentation is needed and a different method to get paths.

Dunno if your interested in Lumin support, but if so hope this helps!

**Comment by napestershine** [comment]
HI

I solved it same day. forgot to update it. It's working like charm.

Thanks :)
