### ISSUE TITLE
Support for Laravel 5.7

### ISSUE THREAD

**Issue by lsfiege** [beyondcode/laravel-self-diagnosis#58]
Can you add support for this new laravel version?

**Comment by tvbeek** [comment]
@lsfiege Doesn't it already support Laravel 5.7? If I'm correctly that is added with version [1.0.2](https://github.com/beyondcode/laravel-self-diagnosis/releases/tag/1.0.2)

**Comment by lsfiege** [comment]
No, it throws an exception by requiring dependency illuminate/support

**Comment by lsfiege** [comment]
Sorry, it was my mistake. I had installed one of the initial versions of this package. Updating the requirement in composer.json to `"beyondcode/laravel-self-diagnosis": "^1.0.2",` worked.
