### ISSUE TITLE
[Question] PhpExtensionsAreInstalled getExtensionsRequiredInComposerFile

### ISSUE THREAD

**Issue by tvbeek** [beyondcode/laravel-self-diagnosis#61]
While writing a test for the PhpExtensionsAreInstalled (as part of #60 )

I did check the getExtensionsRequiredInComposerFile function. But now I'm questioning, how can it fail on extensions from composer if they are already installed?

Because composer will validate the extensions before installing any package it shouldn't be possible to install a package with a requirement that isn't installed. So I suspect that the function is in fact not useful or do I missing something?

**Comment by Namoshek** [comment]
You might have a point there, but here are some scenarios that you might not have thought of just yet:

- PHP is reconfigured and/or extensions (un-)installed after application deployment. This can also happen unexpectedly if extensions are dependencies of other packages and these are removed or updated for example.
- Composer dependencies are installed on a build machine or locally. Then the application with already installed dependencies is pushed to the server (this is actually something I'm using myself as the production server is air gapped from the web, but it may also be used when you run multiple application servers and you don't want to run the build multiple times).
- Composer dependencies are installed with `--ignore-platform-reqs` on purpose, for whatever reason. When using aforementioned build method on another server, this might be required for example.

Personally, I like using the check on our air gapped production server, but I can see that it might not make as much sense on public servers as it does for me.

**Comment by tvbeek** [comment]
@Namoshek Thanks for the explanation.
