### ISSUE TITLE
Suggestion for `PhpExtensionsAreInstalled` check: get expected PHP extensions via config

### ISSUE THREAD

**Issue by mcampbell508** [beyondcode/laravel-self-diagnosis#7]
At the moment the class `\BeyondCode\SelfDiagnosis\Checks\PhpExtensionsAreInstalled` has a specified set of extensions to check. I think it would be useful if this could be done via config, instead, so that the end user can specify their own extensions if they want to. 

Something like :
```diff
    public function check(): bool
    {
-        $this->extensions = Collection::make([
-            'openssl',
-            'PDO',
-            'mbstring',
-            'tokenizer',
-            'xml',
-            'ctype',
-            'json'
-        ]);
+       $this->extensions = Collection::make(config('self-diagnosis.php_extensions', [
+            'openssl',
+            'PDO',
+            'mbstring',
+            'tokenizer',
+            'xml',
+            'ctype',
+            'json'
+       ]));

        $this->extensions = $this->extensions->reject(function ($ext) {
            return extension_loaded($ext);
        });

        return $this->extensions->isEmpty();
    }
```

I am happy to make a merge request, if I can find some time over the next few days.

BTW, this package is awesome!!!! I had similar ideas to this package in the past but never got round to doing anything. Great work as always!

**Comment by Schnoop** [comment]
There is a pull requests for something similar.
I modified the check in a way that all required extensions will be read from the `vendor/composer/installed.json` file:

https://github.com/beyondcode/laravel-self-diagnosis/pull/6

If your application requires some PHP extensions, you can require those in your composer.json file as noted here: https://getcomposer.org/doc/01-basic-usage.md#platform-packages

**Comment by mpociot** [comment]
I applied PR #6 which automatically parses the required extensions from the composer installation json

**Comment by mcampbell508** [comment]
Nice PR @Schnoop !!
