### ISSUE TITLE
Suggestion: Use translations for messaging

### ISSUE THREAD

**Issue by mcampbell508** [beyondcode/laravel-self-diagnosis#8]
At the moment, the message strings returned for each check are tied to the classes themselves. There is no way for the end user to specify their own language, if they would like to.

Example for `\BeyondCode\SelfDiagnosis\Checks\ComposerIsUpToDate`:

```diff
public function message() : string
{
-    return 'Your composer dependencies are not up to date. Call "composer install".' . $this->output;
+    return trans('self-diagnosis.composer-is-up-to-date') . $this->output;
}
```

**Comment by mpociot** [comment]
That's a good idea. Do you want to help me with this by sending a PR?
