### ISSUE TITLE
Error when running on lumen

### ISSUE THREAD

**Issue by abishekrsrikaanth** [beyondcode/laravel-self-diagnosis#81]
I get the following error when running this on lumen

```
Call to undefined method Laravel\Lumen\Application::configurationIsCached()
```

**Comment by davidsivocha** [comment]
Lumen doesn't have Config Caching as a feature (unless you install it)

You want to remove `\BeyondCode\SelfDiagnosis\Checks\ConfigurationIsCached::class` from your list of checks for Self Diagnosis.
