### ISSUE TITLE
Laravel 6.2 compatibility

### ISSUE THREAD

**Issue by fabriciojs** [beyondcode/laravel-self-diagnosis#87]
I have just installed this in a fresh Laravel 6.2 app and it seems there are some inconsistencies.

The Environment specific checks do not work because the way for fetching the environment is broken - is getting only `null`.

That is the only thing I noticed is not working, but that makes me think if the package should be restrained to 5.8, and a new version only - when adjusted accordingly - be available for 6.x.

**Comment by tvbeek** [comment]
Isn't this a problem that is fixed with #86 ?

**Comment by fabriciojs** [comment]
> Isn't this a problem that is fixed with #86 ?

Yes! that is precisely the case, and that solution will work. So this can be closed as soon as it is merged.
