### ISSUE TITLE
Doesn't work with latest laravel version

### ISSUE THREAD

**Issue by EM-LilianaIturribarria** [beyondcode/laravel-self-diagnosis#95]
Using:

- Laravel 7.2.5
- PHP 7.3.19
- composer 1.10.8

```
> php artisan self-diagnosis
|-------------------------------------
| Common Checks
|-------------------------------------


   ErrorException 

  array_key_exists() expects parameter 2 to be array, null given

  at vendor/beyondcode/laravel-self-diagnosis/src/SelfDiagnosisCommand.php:33
    29| 
    30|         $environment = $this->argument('environment') ?: app()->environment();
    31|         $environmentChecks = config('self-diagnosis.environment_checks.' . $environment, []);
    32| 
  > 33|         if (empty($environmentChecks) && array_key_exists($environment, config('self-diagnosis.environment_aliases'))) {
    34|             $environment = config('self-diagnosis.environment_aliases.' . $environment);
    35|             $environmentChecks = config('self-diagnosis.environment_checks.' . $environment, []);
    36|         }
    37| 

      +15 vendor frames 
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

```

**Comment by nagsamayam** [comment]
Hi @EM-LilianaIturribarria 
Please try 
`php artisan config:cache`

before running
`php artisan self-diagnosis`

**Comment by oricis** [comment]
This problem also exist with Laravel 7.30.04 + Composer 2.0 + PHP 8.03. Clear the config solve it.

Step by step:

1. Install the extension: 

    composer require beyondcode/laravel-self-diagnosis

2. Run command: 

    php artisan self-diagnosis

Results:

|-------------------------------------
| Common Checks
|-------------------------------------


   TypeError 

  at vendor/beyondcode/laravel-self-diagnosis/src/SelfDiagnosisCommand.php:33
    29| 
    30|         $environment = $this->argument('environment') ?: app()->environment();
    31|         $environmentChecks = config('self-diagnosis.environment_checks.' . $environment, []);
    32| 
  > 33|         if (empty($environmentChecks) && array_key_exists($environment, config('self-diagnosis.environment_aliases'))) {

***

3. Solve problem: clean the config cache

    php artisan config:clear

4. Check again:

    php artisan self-diagnosis
